# this is an example for config.yaml file, you can rename it to config.yaml if you want to use it
# ###############################################################################################
# you can also use absolute paths like: "/root/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts" or "D:\\comfyui\\custom_nodes\\comfyui_controlnet_aux\\ckpts"
annotator_ckpts_path: "./ckpts"
# if you already have downloaded ckpts via huggingface hub into default cache path like: ~/.cache/huggingface/hub, you can set this True to use symlinks to save space
USE_SYMLINKS: False